### ISSUE TITLE
"reminder" mode for updating OKR in the service gtmhub.com from messenger

### ISSUE THREAD

**Issue by Maay** [dialogs/dialog-okr-bot#3]
In addition to the functionality in issue #1, the bot should allow users to activate the "reminder" mode. If the user activates the reminder mode, the bot sends the user all its key results at a specified time with the ability to update or skip them.

The bot is written in python, so here's the documentation of our Python Bot SDK is here: https://dialogs.github.io/python-bot-sdk/ ⁣

Our messenger has a test instance. Web client that you should use for the development is available here: https://grpc-test.transmit.im/

For web use this endpoint: https://grpc-test.transmit.im:8443
For bots use grpc endpoint: https://grpc-test.transmit.im:9443
Test accounts:
alice / password
After you've logged in you should write to Security Bot user (you can find him in the search field) and write command /bot new bot_username bot_name where bot_username is the username you can choose for your new bot and bot_name is his display name

We've open-sourced several bots that you can look up to for examples https://github.com/dialogs?utf8=%E2%9C%93&q=-bot&type=&language=

Please feel free to ask questions in our community https://dlg.im/@botsfordialog ⁣ ⁣ ⁣ ⁣

How bot should work:

1.1) User: /activate
1.2) *all commands might be canceled by /cancel command
1.3) Bot: Please select day to update OKR with you
1.4) Bot: Dropdown with options: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday
1.5) User chooses Friday
1.6) Bot: Ok, now please reply with time in 16:40 format by Moscow timezone for me to know when to start
1.7) User: 16:20
1.8)Bot: Ok, then each Friday at 16:20 I will start updating okr's with you.

On Friday at 16:20 bot should send user list of all his Objectives and Key Results. User must be able to update them. 

2.1) Bot: It's time to update your OKRs. Ok, let's go
2.2) *Bot sends users OKR in same as in issue #1 format*
```Objective 1](link_to_objective) - completion percentage
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button
...
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button

...

[Objective X](link_to_objective) - completion percentage
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button
...
[Title of the key result](link to the key result) - value - * percentage of completion * - "Refresh" button

```
2.3) User clicks on “Refresh” in one of his key results.
2.4) The bot sends the user a message in the format:

```
The title of the key result
Now - * current_value_key_search_ result *
Must be - * key_result target_value *
Specify a new value.
```
2.5) The user sends a numeric value. If the value does not fit the format, the bot asks to send the correct value.
2.6) The bot sends the user a message in the format: What has changed? Why?
2.7) The user sends any text message.
2.8) The bot sends a message to the user in the format: "Specify the level of confidence in the result [dropdown_to_all_confidence_options]"
2.9) The user selects the result
2.10) The bot sends the user a message in the format:

```
[Key result](link to key result) - new completion percentage
Submit button, Cancel button
```
2.11) The user selects "send" and the bot sends new values to gtmhub.
2.12) The bot sends the user a message: "The result is updated"
2.13) The bot sends the user buttons: "[Next key result to update] [List of all un-updated key results]"

You have to add a check that peer id is equal to sender id in incoming SeqUpdate params. It’s needed to prevent the feature’s mutual influence. For example(Python):

```
def on_msg1(*params):
    if params[0].peer.id == params[0].sender_uid:  # this prevents false reactions 
        bot1.messaging.send_message(
            …
        )
```		
		
For bounty to be verified, it’s necessary to create documentation for it, and functionality should be covered by tests. The bot should be accompanied by a valid Dockerfile, in which the bot will run. All the phrases should be stored in locales file.

**Comment by Maay** [comment]
@willy2dg are you interested in [this](https://www.bountysource.com/issues/75054826-reminder-mode-for-updating-okr-in-the-service-gtmhub-com-from-messenger)?

**Comment by willy2dg** [comment]
Yes @Maay , I'm interested. although first I need to read a bit about the dockerfile, since I'm not familiar with it. What kind of tests do you need ?

**Comment by Maay** [comment]
@willy2dg unit tests for basic functionality

**Comment by willy2dg** [comment]
Ok @Maay , I'll plan it more in depth and in a couple of days I'll tell you my doubts about the details, if it seems right to you.

**Comment by Maay** [comment]
@willy2dg sure, any details might be changed if you see any better solution for the task.

**Comment by Maay** [comment]
@willy2dg so what do you think?

**Comment by willy2dg** [comment]
Hi @Maay , just some point to clarify.

1 - Scheduller will run on python inside the bot instance, right ?
2 - Bot is expected to use locale files per instance, ( signle instance single language ) ?
3 - You want to translate the commands ?
4 - Can be the tests just for the internal classes ( no API interactions ) with fake data ? 

I think its all, i added the "overview" functionallity as command too, so if some one was using the bot when the reminder fires the overview will be replaced with a message.

**Comment by Maay** [comment]
@willy2dg 
1) Right
2) No, for everyone
3) Yes, we will use bot in Russian
4) API interactions should be covered by tests as well

OK

**Comment by willy2dg** [comment]
Ok, but about point 4, the bot doesn't create/remove data, so for testing you need to know the resulting data from API calls and anyways data will change over the time, then will be useless tests if you haven't a static test enviroment. The GtmHub API documentation provide forms to perform API calls, but my test user was expired, could you give me the test data if i give you the methods list ( are 5 if i remember correctly )

**Comment by Maay** [comment]
@willy2dg sure, we will provide you with test user!

**Comment by willy2dg** [comment]
@Maay Fine, that's much better, just keep in mind the comment above, since working with the API will deprecate the unit tests, but i can do it. If i don't go crazy with the tests hope send you a PR before the weekend.

**Comment by moleculaman** [comment]
@willy2dg give me, please, your email - i'll add you to test gtmhub project

**Comment by willy2dg** [comment]
Hi @moleculaman , use manecollons@gmail.com . You can send there the API token and account-id too .

**Comment by willy2dg** [comment]
How is it going @moleculaman ?

**Comment by moleculaman** [comment]
@willy2dg well, gtmhub support said, that they cant add @gmail users, so i send credentials to our test environment on your email, check it

**Comment by willy2dg** [comment]
Hi @Maay @moleculaman , i sent a PR . Unfortunately my IDE breaked my repository some how, so all changes are in a single commit . I don't tested it on Docker, but i based my file on others from your bots and should be working. Tests are working and testing manually seems to be working too. 
I wait for your feedback.

**Comment by Drymonade** [comment]
@willy2dg Hi there. When I type `/okr [[My Name]]`, bot sent me all of our company's OKRs, not only my. Earlier this worked fine.

**Comment by willy2dg** [comment]
I am sorry @Drymonade @moleculaman , these was the single part i can't tested and was changed since there was a bug. I updated my PR to add test cases for it and the error should be fixed too.

**Comment by Drymonade** [comment]
@willy2dg Yeah, now name filter works, but only in direct messages. When I schedule the reminder, it reply with all OKR's, not only my ones. It's possible to specify the name of reminded person in reminder activation dialog.

**Comment by willy2dg** [comment]
Hi @Drymonade , now the reminder asks for username, and you can use the user/list filters for the /overview command too.

**Comment by Drymonade** [comment]
@willy2dg Ok, now it's great. Thanks a lot! Closing this issue.

**Comment by Maay** [comment]
@willy2dg please claim bounty on bountysource! Thank you for your work

**Comment by willy2dg** [comment]
I sent a bounty claim @Maay , thanks to you.
